### ISSUE TITLE
Artifact uploading broken

### ISSUE THREAD

**Issue by afeld** [frictionlessdata/repository#57]
Hey there-
This action is being used for the dataportals.org repository, but it's [failing](https://github.com/okfn/dataportals.org/actions/runs/15229982488/job/42836668753) with:

> Error: Cannot upload inquiry: Create Artifact Container failed: The artifact name inquiry is not valid. Request URL https://pipelinesghubeus2.actions.githubusercontent.com/2UQuvIJpDWjrmbwORwOrXieAxeoagnl688roNjITbjlvRlym1L/_apis/pipelines/workflows/15229982488/artifacts?api-version=6.0-preview

My guess is this is because it's using an old version of the [`@actions/artifact` package](https://www.npmjs.com/package/@actions/artifact), which uses a deprecated API.

Thanks!

**Comment by afeld** [comment]
Also, in case anyone else hits this issue: It's pretty straightforward to switch to using the [Frictionless CLI](https://v4.framework.frictionlessdata.io/docs/tutorials/working-with-cli) directly. Example:

```yaml
- name: Checkout repository
  uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: "3.13"
- name: Install dependencies
  run: pip install "frictionless==5.*"
- name: Validate data
  run: frictionless validate data/datapackage.json
```
